resources:
  repositories:
    - repository: BrokerIdAzurePipelines
      type: git
      name: BrokerIdAzurePipelines

trigger:
  branches:
    exclude:
      - 'v*'

pool:
  name: Hosted Ubuntu 1604
  demands: npm

variables:
  - template: variables.yaml@BrokerIdAzurePipelines

steps:
  - template: lambda_pipeline.yaml@BrokerIdAzurePipelines
